const ChartConfig = {
  general: {
    stockWindow: 40000,
    zone: "current",
  },
  indicatorSettings: {
    ema10: {
      parameter: "ema,10",
      ownPane: false,
      color: "#555",
    },
    ema20: {
      parameter: "ema,20",
      ownPane: false,
      color: "#002d99",
    },
    ema50: {
      parameter: "ema,50",
      ownPane: false,
      color: "#9d39f3",
    },
    sma100: {
      parameter: "sma,100",
      color: "#ff00ff",
      ownPane: false,
    },
    sma200: {
      parameter: "sma,200",
      ownPane: false,
      color: "#78465e",
    },
    // ema10: {
    //   parameter: "ema,10",
    //   ownPane: false,
    //   color: "#AE2EAE",
    // },
    // ema20: {
    //   parameter: "ema,20",
    //   ownPane: false,
    //   color: "#FF0055",
    // },
    bb: {
      parameter: "bb,20,2.5",
      ownPane: false,
      color: "#000000",
    },
    closemain: {
      parameter: "closemain",
      color: "#FFFF55",
      ownPane: false,
    },
    adx: {
      yAxisName: "adx_yaxis",
      parameter: "adx",
      ownPane: true,
      color: "#FF55AA",
      colorAdx: "#111111",
      colorDiPlus: "#2AFF2A",
      colorDiMinus: "#FF55D4",
      height: 150,
    },
    macd: {
      yAxisName: "macd_yaxis",
      parameter: "macd,26,12,9",
      ownPane: true,
      color: "#FF55AA",
      colorMacd: "#002d99",
      colorSignal: "#9d39f3",
      colorHist: "#3256a8",
      height: 140,
    },
    heikin: {
      yAxisName: "heikin_yaxis",
      parameter: "heikin",
      ownPane: true,
      color: "#AAAAFF",
      height: 150,
    },
    stochastic: {
      yAxisName: "stochastic_yaxis",
      parameter: "stochastic,14,3",
      ownPane: true,
      color: "#FFAA00",
      colorK: "#002d99",
      colorD: "#9d39f3",
      height: 120,
      threshold1: 30,
      threshold2: 70,
    },
    rsi: {
      yAxisName: "rsi_yaxis",
      parameter: "rsi,6",
      ownPane: true,
      color: "#7F2AFF",
      colorRsi: "#AAFFFF",
      height: 100,
    },
    william: {
      yAxisName: "willaim_yaxis",
      parameter: "william,14",
      ownPane: true,
      color: "#5500c5",
      height: 110,
      threshold1: -20,
      threshold2: -80,
    },
  },
};

export default ChartConfig;
